services:
  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_DATABASE=test
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=admin
  #   volumes:
  #     # seeding scripts
  #     - ./mongo-entrypoint:/docker-entrypoint-initdb.d
  #     # named volumes
  #     - ./db/mongodb:/data/db
  #     - ./db/mongoconfig:/data/configdb
  #   networks:
  #     - mongo_network

  backend:
    image: land-docs-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/api
      - /api/node_modules
    container_name: land-docs-backend
    stdin_open: true
    networks:
      - mongo_network
    # depends_on: [mongodb]

  frontend:
    image: land-docs-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # env_file:
    #   - .env
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: land-docs-frontend
    stdin_open: true
    depends_on: [backend]

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Mount your Nginx configuration file
  #   ports:
  #     - "80:80" # Expose Nginx on port 80
  #   depends_on:
  #     - godaesil-api
